% This file is generated by SEPIA version: v1.2.2.6
% add general Path
sepia_addpath;

% Input/Output filenames
input = struct();
input(1).name = 'H:\My Drive\Maitrise\Project\Data\first qsm trial\Patient_3\Phase_data.nii.gz' ;
input(2).name = 'H:\My Drive\Maitrise\Project\Data\first qsm trial\Patient_3\Magnitude_data.nii.gz' ;
input(3).name = '' ;
input(4).name = 'D:\Poly_MSc_Code\libraries_and_toolboxes\sepia_header.mat' ;
output_basename = 'H:\My Drive\Maitrise\Project\Data\first qsm trial\Patient_3\output\Sepia' ;
mask_filename = ['H:\My Drive\Maitrise\Project\Data\first qsm trial\Patient_3\pat3_mask.nii.gz'] ;

% General algorithm parameters
algorParam = struct();
algorParam.general.isBET = 0 ;
algorParam.general.isInvert = 0 ;
algorParam.general.isRefineBrainMask = 0 ;
% Total field recovery algorithm parameters
algorParam.unwrap.echoCombMethod = 'Optimum weights' ;
algorParam.unwrap.unwrapMethod = 'Laplacian (MEDI)' ;
algorParam.unwrap.isEddyCorrect = 0 ;
algorParam.unwrap.isSaveUnwrappedEcho = 1 ;
% Background field removal algorithm parameters
algorParam.bfr.refine_method = 'Spherical harmonic' ;
algorParam.bfr.refine_order = 2 ;
algorParam.bfr.erode_radius = 0 ;
algorParam.bfr.erode_before_radius = 0 ;
algorParam.bfr.method = 'LBV' ;
algorParam.bfr.tol = 0.0001 ;
algorParam.bfr.depth = 5 ;
algorParam.bfr.peel = 2 ;
% QSM algorithm parameters
algorParam.qsm.reference_tissue = 'None' ;
algorParam.qsm.method = 'TKD' ;
algorParam.qsm.threshold = 0.15 ;

sepiaIO(input,output_basename,mask_filename,algorParam);
