% This file is generated by SEPIA version: v1.2.2.6
% add general Path
sepia_addpath;

% Input/Output filenames
input = struct();
input(1).name = 'H:\My Drive\Maitrise\Project\Data\first qsm trial\Patient_2\fmap.nii.gz' ;
input(2).name = '' ;
input(3).name = '' ;
input(4).name = 'H:\My Drive\Maitrise\Project\Data\first qsm trial\sepia_header.mat' ;
output_basename = 'H:\My Drive\Maitrise\Project\Data\first qsm trial\Patient_2\Sepia-outputs\trial11\Sepia' ;
mask_filename = ['C:\Users\User\QSM_data\patient1\mask.nii.gz'] ;

% General algorithm parameters
algorParam = struct();
algorParam.general.isBET = 0 ;
algorParam.general.isInvert = 0 ;
algorParam.general.isRefineBrainMask = 0 ;
% Background field removal algorithm parameters
algorParam.bfr.refine_method = 'None' ;
algorParam.bfr.refine_order = 4 ;
algorParam.bfr.erode_radius = 0 ;
algorParam.bfr.erode_before_radius = 0 ;
algorParam.bfr.method = 'LBV' ;
algorParam.bfr.tol = 0.0001 ;
algorParam.bfr.depth = -1 ;
algorParam.bfr.peel = 1 ;

sepiaIO(input,output_basename,mask_filename,algorParam);
